/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Cactoro({active, hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Cactoro.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = active ? "Walk" : hovered ? "Wave" : 'Idle'
    actions[anim].reset().fadeIn(0.5).play()

    return () => actions[anim].fadeOut(0.5)
  }, [hovered, active])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh
        geometry={nodes.Cube120.geometry}
        material={materials.Cactoro_Main}
        skeleton={nodes.Cube120.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube120_1.geometry}
        material={materials.Cactoro_Secondary}
        skeleton={nodes.Cube120_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube120_2.geometry}
        material={materials.Cactoro_Red}
        skeleton={nodes.Cube120_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube120_3.geometry}
        material={materials.Eye_Black}
        skeleton={nodes.Cube120_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube120_4.geometry}
        material={materials.Eye_White}
        skeleton={nodes.Cube120_4.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube120_5.geometry}
        material={materials['Cactoro_Main.001']}
        skeleton={nodes.Cube120_5.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/models/Cactoro.gltf')
