/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Dragon({active, hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Dragon.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = active ? "Fast_Flying" : hovered ? "Punch" : 'Flying_Idle'
    actions[anim].reset().fadeIn(0.5).play()

    return () => actions[anim].fadeOut(0.5)
  }, [hovered, active])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh
        geometry={nodes.Cube221.geometry}
        material={materials.Dragon_Main}
        skeleton={nodes.Cube221.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube221_1.geometry}
        material={materials.Dragon_Secondary}
        skeleton={nodes.Cube221_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube221_2.geometry}
        material={materials.Dragon_Horn}
        skeleton={nodes.Cube221_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube221_3.geometry}
        material={materials.Eye_Black}
        skeleton={nodes.Cube221_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube221_4.geometry}
        material={materials.Eye_White}
        skeleton={nodes.Cube221_4.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/models/Dragon.gltf')
