/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Fish({active, hovered, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Fish.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const anim = active ? "Walk" : hovered ? "Wave" : 'Idle'
    actions[anim].reset().fadeIn(0.5).play()

    return () => actions[anim].fadeOut(0.5)
  }, [hovered, active])

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh
        geometry={nodes.Sphere026.geometry}
        material={materials.Fish_Main}
        skeleton={nodes.Sphere026.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sphere026_1.geometry}
        material={materials.Fish_Secondary}
        skeleton={nodes.Sphere026_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sphere026_2.geometry}
        material={materials.Eye_Black}
        skeleton={nodes.Sphere026_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sphere026_3.geometry}
        material={materials.Eye_White}
        skeleton={nodes.Sphere026_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sphere026_4.geometry}
        material={materials.Mouth}
        skeleton={nodes.Sphere026_4.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sphere026_5.geometry}
        material={materials.Fish_Flaps}
        skeleton={nodes.Sphere026_5.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/models/Fish.gltf')
